version: '0.1'
services:
  api:
    container_name: secrets_api
    build: './secrets'
    volumes:
      - ./creds:/api/creds/:ro # change this to the local secrets folder
  telelgram:
    container_name: telegram_bot
    build: './telegram_bot'
    ports:
      - "50001:5000"
    depends_on:
      api:
        condition: service_healthy
  discord:
    container_name: discord_bot
    build: './discord_bot'
    ports:
      - "50002:5001"
    depends_on:
      api:
        condition: service_healthy
